import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {Toaster} from "sonner";
import Navbar from "@/components/navbar";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Client register",
    description: "Generated by create next app",
};

export default function RootLayout(
    {children,}: Readonly<{ children: React.ReactNode; }>
) {
    return (
        <html lang="en" >
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} >
        <Navbar />
        <div className="relative w-full mx-auto m-0 py-24 md:py-36" >
            {children}
        </div >
        <Toaster />
        </body >
        </html >
    );
}
